---
title: "ggvis"
author: "JWC"
date: "21/02/2017"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## ggvis at a glance

Rich Interactive Graphics

## let's get started

```{r cars}
library(ggvis)
head(mtcars)
```

## recipe #1: scatter plot

```{r cars_plot}
mtcars %>% 
  ggvis(~wt, ~mpg) %>% 
  layer_points(fill = ~factor(cyl))
```

## recipe #2: bar graphs

```{r}
head(pressure)
```

## recipe #2: bar graphs

```{r}
pressure %>%
  ggvis(~temperature, ~pressure) %>%
  layer_bars(width =10)
```

## now sprinkle on some interactivity

- input_slider
- input_select
- input_checkbox()
- input_checkboxgroup()
- input_radiobuttons()

## plot it

```{r, echo=FALSE}
mtcars %>% ggvis(x = ~wt) %>%
    layer_densities(
      adjust = input_slider(.1, 2, value = 1, step = .1, label = "Bandwidth adjustment"),
      kernel = input_select(
        c("Gaussian" = "gaussian",
          "Epanechnikov" = "epanechnikov",
          "Rectangular" = "rectangular",
          "Triangular" = "triangular",
          "Biweight" = "biweight",
          "Cosine" = "cosine",
          "Optcosine" = "optcosine"),
        label = "Kernel")
    )
```

## More recipes
https://github.com/jlow2499/ggvis-examples/blob/master/interactiveplots1.R

```{r, echo=FALSE}
faithful %>% 
  ggvis(~waiting, ~eruptions, fillOpacity := 0.5, 
        shape := input_select(label = "Choose shape:", 
                              choices = c("circle", "square", "cross", "diamond", 
                                          "triangle-up", "triangle-down"))) %>% 
  layer_points()
```

## More recipes
https://github.com/jlow2499/ggvis-examples/blob/master/interactiveplots1.R

```{r, echo=FALSE}
faithful %>% 
  ggvis(~waiting, ~eruptions, fillOpacity := 0.5, 
        shape := input_select(label = "Choose shape:", 
                              choices = c("circle", "square", "cross", 
                                          "diamond", "triangle-up", "triangle-down")), 
        fill := input_select(label = "Choose color:", 
                             choices = c("black", "red", "blue", "green"))) %>% 
  layer_points()
```

## More recipes 
https://github.com/jlow2499/ggvis-examples/blob/master/interactiveplots1.R

```{r, echo=FALSE}
mtcars %>% 
  ggvis(~mpg, ~wt, 
        fill := input_radiobuttons(label = "Choose color:", 
                                   choices = c("black", "red", "blue", "green"))) %>% 
    layer_points()
```

